# Generated by Django 5.0.2 on 2024-02-19 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='cart_id',
            new_name='wishlist_id',
        ),
    ]
