# Generated by Django 5.0.2 on 2024-02-19 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_rename_cart_id_wishlist_wishlist_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistitems',
            name='total',
        ),
    ]
