# Generated by Django 5.0.2 on 2024-02-24 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listingitem',
            old_name='order',
            new_name='listing',
        ),
    ]
