# Generated by Django 5.0.2 on 2024-02-24 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_rename_order_listingitem_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listingitem',
            name='quantity',
        ),
    ]
