# Generated by Django 5.0.2 on 2024-02-25 07:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_remove_listingitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='booking_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
