# Generated by Django 5.0.2 on 2024-02-26 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listing_booking_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='hostel_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
