# Generated by Django 5.0.2 on 2024-02-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listing_hostel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='phone_number',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
