# Generated by Django 5.0.2 on 2024-02-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_listing_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='hostel_name',
            field=models.CharField(default='group 1 hostel', max_length=100),
            preserve_default=False,
        ),
    ]
