# Generated by Django 5.0.2 on 2024-03-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_listing_hostel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='ref',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ListingItem',
        ),
    ]
