# Generated by Django 5.0.2 on 2024-03-01 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_listing_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='booking_number',
        ),
    ]
