# Generated by Django 5.0.2 on 2024-02-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=250)),
                ('slug', models.CharField(max_length=500, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
