# Generated by Django 5.0.2 on 2024-02-18 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='location',
            new_name='location_name',
        ),
    ]
