# Generated by Django 5.0.2 on 2024-02-18 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel_name', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=400, unique=True)),
                ('stock', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('hostel_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('hostel_description', models.TextField()),
                ('hostel_image', models.ImageField(upload_to='hostel_main_image')),
                ('hostel_bedroom', models.ImageField(blank=True, upload_to='hostel_bedroom')),
                ('hostel_kitchen', models.ImageField(blank=True, upload_to='hostel_kitchen')),
                ('hostel_washroom', models.ImageField(blank=True, upload_to='hostel_washroom')),
                ('hostel_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.location')),
                ('hostel_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
